Vet Clinic Database Exercise - Milestone 4: Join Table
AyoubMs/vet_clinic pull request #8
Opened 2022-06-02 21:01 UTC by AyoubMs

In this milestone, I:
- Inserted data to the following tables:
  * vets table
  * specializations table

2022-06-02 21:22 UTC, mmsesay requested changes
Hi @AyoubMs, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] What do you think about improving the project title on the readme from `curriculum-databases-projects-template` to `Vet Clinic Database` or something else?

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 21:22 UTC, mmsesay commented on data.sql
> +INSERT INTO vets (name, age, date_of_graduation) VALUES('Maisy Smith', 26, '2000-01-17');
- [x] The graduation date for this vet should be `2019-01-17` instead of `2000-01-17`. I believe we can refactor it here.

2022-06-02 21:22 UTC, mmsesay commented on data.sql
> +INSERT INTO vets (name, age, date_of_graduation) VALUES('Stephanie Mendez', 64, '2000-05-04');
- [ ] Vet `Stephanie Mendez` graduation date should be `1981-05-17` instead of `2000-05-04`. We can work on this as well.

2022-06-03 07:57 UTC, CollinsTatang approved these changes
# Approved 👏  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 07:58 UTC, merged